### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by jkavanaghrdm** [cnblogs/EnyimMemcachedCore#127] opened 2019-08-07 15:17 UTC
We have been unable to get plain text authentication working for our memcached integration. Memcached has been configured to enable SASL and that has been proven to be operational on the server, however, when we try to use this memcachedcore package and provide the zone and credentials we get "Authentication failure" errors logged on the memcached server when we try to get and store values. I checked the issue log but haven't come across anything relevant. Is this a known issue or an issue with a known fix. Any help you can provide is appreciated.

**Comment by grriffin** [comment] 2019-08-22 17:33
This appears to be caused by the UseEnyimMemcached extension calling GetResultAsync().Wait(). BinaryNode has no override for CreateSocketAsync, so the sockets in the pool were created without the authentication being called. Writing a custom "Use" extension that just calls Get() instead of the Async version fixed the issue. It could also be fixed with adding a CreateSocketAsync override.

**Comment by cnblogs-dudu** [comment] 2019-09-15 01:25
Fixed in EnyimMemcachedCore 2.4.0.

**Closed** 2019-09-25 14:55 UTC
